[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
PiccoloQuantumObjects = "5a402ddf-f93c-42eb-975e-5582dcda653d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
